# Site settings
title: Jason Divock
email: jdivock@gmail.com
description: > # this means to ignore newlines until "baseurl:"
             Jason Divock, JavaScript Developer @ Box helping to build Front-End Tooling and Frameworks.
             Playing with React, CLJS, RxJs, and ES6/7 in my spare time.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jdivock.com" # the base hostname & protocol for your site
twitter_username: jdivock
github_username:  jdivock

# Build settings
markdown: kramdown


