# Site settings
title: Jason Divock
email: jdivock@gmail.com
description: > # this means to ignore newlines until "baseurl:"
             Just a landing page cause something had to be here. Maybe some eventual ramblings
             about life @ Box.com, Clojure/ClojureScript, React, and anything else I fance. Just
             this for now
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jdivock.com" # the base hostname & protocol for your site
twitter_username: jdivock
github_username:  jdivock

# Build settings
markdown: kramdown


